apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura.adminSecretName" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "hasura.serviceAccountName" . }}
type: Opaque
data:
  admin: {{ .Values.hasuraConfig.adminSecret | b64enc | quote }}
