apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hasura.configMapName" . }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
data:
  HASURA_GRAPHQL_DATABASE_URL: {{.Values.hasuraConfig.databaseUrl }}
  HASURA_GRAPHQL_ENABLE_CONSOLE: {{.Values.hasuraConfig.enableConsole | quote }}
  HASURA_GRAPHQL_DEV_MODE: {{.Values.hasuraConfig.devMode | quote }}
